# Generated by Django 2.0.6 on 2018-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(default='未知', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='DevoterName',
            field=models.CharField(default='未知', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='未知', max_length=100),
        ),
    ]
