# Generated by Django 2.0.6 on 2018-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180708_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Translator',
            field=models.CharField(default='无', max_length=100),
        ),
    ]
