# Generated by Django 2.0.6 on 2018-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='FrontPage',
            field=models.FileField(default='static\no_frontpage.png', max_length=400, upload_to=''),
        ),
    ]
