# Generated by Django 2.0.7 on 2018-07-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='DevoterName',
        ),
        migrations.RemoveField(
            model_name='book',
            name='User',
        ),
    ]
