# Generated by Django 2.0.7 on 2018-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_borrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='FrontPage',
            field=models.CharField(default='static\no_frontpage.png', max_length=400),
        ),
    ]
