# Generated by Django 2.0.7 on 2018-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_remove_book_isborrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
