# Generated by Django 2.0.7 on 2018-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20180822_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='FrontPage',
            field=models.CharField(default='static/no_frontpage.png', max_length=400),
        ),
    ]
